name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: sample-python-app
      NEXUS_URL: 3.82.16.193:8083
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Unit Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest tests/

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=sample-python-app
          -Dsonar.sources=src
          -Dsonar.tests=tests
          -Dsonar.host.url=$SONAR_HOST_URL
          -Dsonar.login=$SONAR_LOGIN

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:latest .

    - name: Tag and Push to Nexus
      run: |
        docker tag $IMAGE_NAME:latest $NEXUS_URL/$IMAGE_NAME:latest
        echo $NEXUS_PASS | docker login http://$NEXUS_URL -u $NEXUS_USER --password-stdin
        docker push $NEXUS_URL/$IMAGE_NAME:latest
